version: '3.7'
services:
  aflt_api:
    image: 242617/test-app:v0.0.2
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    #   - ./repos.yaml:/app/repos.yaml:ro
    #   - ./stacks.yaml:/app/stacks.yaml:ro
